### ISSUE TITLE
Ability to add properties for strategy/hider

### ISSUE THREAD

**Issue by Trampeltier** [jotoh98/treasureHunt#112]
It would be convenient if a strategy or a hider could add properties (constants) which can be set in the GUI.
For example one would like to choose the maximum angle a hider can give (1 to 359 degrees).
It could also be handy for many other constants.

**Comment by Trampeltier** [comment]
Also useful if a strategy has possible multiple substrategies to choose one from.

**Comment by jotoh98** [comment]
fixed by #178 ?
