### ISSUE TITLE
Add possiblility of committing GeometryItems at initialization

### ISSUE THREAD

**Issue by rukemn** [jotoh98/treasureHunt#146]
Right now, GeometryItems can only be commited with a Hint,
which prevent the Display of an algorithms initial State.
Maybe use List<GeometryItems> on signature to accomodate for this

**Comment by jotoh98** [comment]
There‘s already a `Searcher.move()` method without parameters for the first movement. Do you suggest a new searcher method to be called at the `GameEngine.init()` method (thus changing the interface) or do we need to change the game engine‘s methods?
