### ISSUE TITLE
Make Hint, SearchPath, Treasure selectable

### ISSUE THREAD

**Issue by DorianRec** [jotoh98/treasureHunt#181]
Since on every rendering, new GeometryItems are created,
we are unable to manipulate them.
This is essential for #51.

**Comment by 1-alex98** [comment]
or u overwrite the equals method in a meaning ful way

**Comment by DorianRec** [comment]
> or u overwrite the equals method in a meaning ful way

Better idea: The Hints, SearchPaths and Treasure Objects get selected,
and they create GeometryItems for printing them on canvas or do calculations with them.

**Comment by 1-alex98** [comment]
No idea what you mean just make sure that clicking and selecting items stays on its own and does not interfere with the general work flow. Items do not need to know if they are selected if u ask me.
