### ISSUE TITLE
Seperate Visuals (like ImageItem) and GeometryItems

### ISSUE THREAD

**Issue by DorianRec** [jotoh98/treasureHunt#182]

**Comment by 1-alex98** [comment]
U want that for your click stuff

**Comment by DorianRec** [comment]
> U want that for your click stuff

Yes and for a cleaner code.
An image has nothing to do with GeometryItem objects,
since every GeometryItem contain a Geometry

**Comment by 1-alex98** [comment]
I disagree. They are all meant for displaying extra information. If you don't want them to be click able(which they could) then I would suggest filtering them out.
