### ISSUE TITLE
Quit program correctly

### ISSUE THREAD

**Issue by DorianRec** [jotoh98/treasureHunt#216]
Clicking the "x" does not quits the program
<img width="246" alt="Bildschirmfoto 2020-03-16 um 13 06 05" src="https://user-images.githubusercontent.com/14947840/76756970-07f58c00-6787-11ea-8bac-da7e6c79035e.png">

**Comment by jotoh98** [comment]
It does after a few seconds. It's not of immediate effect because of the javafx-wrapper
