### ISSUE TITLE
Bad color selection

### ISSUE THREAD

**Issue by DorianRec** [jotoh98/treasureHunt#217]
If the room is not dark, this is pretty hard to read:
<img width="236" alt="Bildschirmfoto 2020-03-16 um 13 12 22" src="https://user-images.githubusercontent.com/14947840/76757410-cdd8ba00-6787-11ea-9015-79d1d22d3e1d.png">

**Comment by jotoh98** [comment]
Shouldn't we delete this upper inspector section altogether? (And improve the textual representation underneath?)

**Comment by DorianRec** [comment]
> Shouldn't we delete this upper inspector section altogether? (And improve the textual representation underneath?)

 ++
