### ISSUE TITLE
Please show available preferences. (Dropdown)

### ISSUE THREAD

**Issue by DorianRec** [jotoh98/treasureHunt#218]
Since it is hard to guess, which preferences are possible,
show the available preferences keywords (via Dropdown).
<img width="283" alt="Bildschirmfoto 2020-03-16 um 13 18 06" src="https://user-images.githubusercontent.com/14947840/76757789-96b6d880-6788-11ea-9f52-ed5915f3dae9.png">

**Comment by jotoh98** [comment]
The available preferences are automatically added to the table behind the popup. Should we change it to a dropdown?

**Comment by 1-alex98** [comment]
na i think it is ok the way it is
