### ISSUE TITLE
Make all Searcher<AngleHint> to HideAndSeekSearcher<AngleHint>

### ISSUE THREAD

**Issue by rukemn** [jotoh98/treasureHunt#272]
Unless its a cheating strategy nothing would change for a Searcher if the Hider is allowed to move the treasure during the run (as long as the Hider doesn't cheat of course)

**Comment by jotoh98** [comment]
You want to move the generic funtionality not just for AngleHint right?

And does this imply, that we can drop the GameEngine dropdown? That would shorten and improve the MainController a lot.

**Comment by rukemn** [comment]
For a searcher it shouldn't make a difference.
For a hider it does, since a different strategy is probably used.

It might be interesting from a scientific point of view to compare what impact on the constant a relocation of the treasure has.

I would recommend to leave the GameEngines as is.
Simply add the HideAndSeek Interface to all searchers if there's no compelling argument against it.

**Comment by DorianRec** [comment]
Yes, for the searcher it is a difference, whether he is playing HideAndSeek or not.
For example a PolygonSearcher, keeping a polygon with the possible treasure location, which he is trying to minimize, cannot play HideAndSeek, since the treasure could move outside this polygon.

**Comment by rukemn** [comment]
the PolygonSearcher can only get his information from hints. As I understand the game a HideAndSeek-Game means the hider can move the treasure in any of his moves, BUT
any previously given hint must be compatible with the new treasure e.g. the treasure must be inView of all the previous hints. 
And since the searcher cannot know the treasure location ahead of finding it, it cannot make a difference right?
As I understand the the HideAndSeek Mode it's only meant for getting the last few units of pathlength out of the searcher in order to get a better approximation for the Constant we are looking for
