### ISSUE TITLE
changing 2 to 1

### ISSUE THREAD

**Issue by anLeid** [jotoh98/treasureHunt#291]
necessary

**Comment by DorianRec** [comment]
This seems to be fixed, when the branch [bugfix/#285-poly-tight-search-area-bug](https://github.com/jotoh98/treasureHunt/tree/bugfix/%23285-poly-tight-search-area-bug) is merged. See commit [2b4ff13
](https://github.com/jotoh98/treasureHunt/commit/2b4ff138e342ccf19c28880630675b752c8a8036)
