### ISSUE TITLE
Unfortunately, no Searcher/Hider/Engine is pre-selected.

### ISSUE THREAD

**Issue by DorianRec** [jotoh98/treasureHunt#323]
Unfortunately, the pre-selection of Searcher/Hider/Engine is gone.

**Comment by jotoh98** [comment]
The pre-selection is a session feature. If you're not saving a session by closing a window with the default closing button (by stopping in intellij for example), the session is not updated. We could update a session by changing the selection. Is this a feature request?

**Comment by DorianRec** [comment]
> The pre-selection is a session feature. If you're not saving a session by closing a window with the default closing button (by stopping in intellij for example), the session is not updated. We could update a session by changing the selection. Is this a feature request?

Oh, youre right, I did not save a session,
but updating a session by changing the selection is a very good idea!
Ill open a new issue! (#330)

**Comment by DorianRec** [comment]
Hmm, seems that this feature not always works
