### ISSUE TITLE
Implement the early exit functionality for the treasure

### ISSUE THREAD

**Issue by DorianRec** [jotoh98/treasureHunt#334]
Please, also implement the early exit functionality for the treasure, meaning
For example the Searcher has to approach 3 LE in the direction to the treasure, after each move.

Should be the same functionality implemented for issue #283

**Comment by jotoh98** [comment]
Does this account for the last point of each SearchPath? Or average? Or both with a secondary Preference?

**Comment by DorianRec** [comment]
> Does this account for the last point of each SearchPath? Or average? Or both with a secondary Preference?

I meant the first one (f.e. on each move, the searcher has to be 3 LE closer to the treasure). But your second option is also a good idea! ^^
