### ISSUE TITLE
Question for early exit metric

### ISSUE THREAD

**Issue by DorianRec** [jotoh98/treasureHunt#335]
I got a question for the early exit metric implemented in #283:

Why is early_exit only working for EARLY_EXIT_AMOUNT >= 2 and EARLY_EXIT_RADIUS>1e-10 ?
Seems to be useful, if it would also work for EARLY_EXIT_AMOUNT = 1 (If we want the Searcher to move a distance of X in each time, also arbitrary small EARLY_EXIT_RADIUS seem to be useful.

**Comment by jotoh98** [comment]
EARLY_EXIT_AMOUNT ist the amount of points in the circle scanned from the middle of the set of points. So if I scan for a set of 1 points from one point and the EARLY_EXIT_RADIUS > 0, the early exit attribute is always met thus ending the game.

**Comment by DorianRec** [comment]
> EARLY_EXIT_AMOUNT ist the amount of points in the circle scanned from the middle of the set of points. So if I scan for a set of 1 points from one point and the EARLY_EXIT_RADIUS > 0, the early exit attribute is always met thus ending the game.

Thank you for the quick answer!
The last question is, why can the EARLY_EXIT_RADIUS only be > 1e-10 ? Is this rounded to 0 ?

**Comment by DorianRec** [comment]
solved
