### ISSUE TITLE
Tracelength is not calculated correctly in the last step

### ISSUE THREAD

**Issue by rukemn** [jotoh98/treasureHunt#350]
Scenario: 
a searcherStrategy which puts multiple Points in the Searchpath.
somewhere on the path is the treasure. 

The statistic for tracelength is now incorrectly calculated.
the path should only count until the treasure was seen the first time. It currently calculates the length as if the whole path was walked. 

I suggest to remeasure the distance for the last searchpath if the treasure was found. 
Measure the distance from the correct LineSegment to the treausure and calculate the distance by projecting the point onto the line ( still off by ~1).

**Comment by DorianRec** [comment]
> Scenario:
> a searcherStrategy which puts multiple Points in the Searchpath.
> somewhere on the path is the treasure.
> 
> The statistic for tracelength is now incorrectly calculated.
> the path should only count until the treasure was seen the first time. It currently calculates the length as if the whole path was walked.
> 
> I suggest to remeasure the distance for the last searchpath if the treasure was found.
> Measure the distance from the correct LineSegment to the treausure and calculate the distance by projecting the point onto the line ( still off by ~1).

Did you mean the problem, stated in this issue #168 ?
I am working on that :P
