### ISSUE TITLE
Make Statistic Widget Scrollable

### ISSUE THREAD

**Issue by rukemn** [jotoh98/treasureHunt#368]
When there's too many items in the statistics widget, the bottom ones are cut off. 
Please add some kind of scrolling functionality or pagination.

**Comment by jotoh98** [comment]
Please specify: The upper left statistics widget for the current run or do you mean the mass statistics tables?

**Comment by jotoh98** [comment]
I have tested it: Every table in Javafx is embedded in a TableView with their own scroll-bars.
Gonna mark this issue as closed due to not an issue. @rukemn
