### ISSUE TITLE
The ability to set up and run multiple instances and case scenarios in empty view 

### ISSUE THREAD

**Issue by anLeid** [jotoh98/treasureHunt#54]
It has been requested that one can run multpile problem instances in empty view in order to analyse data for many problem instances. In the first place it has to be implemented:
- [ ] Add return-data from finished strategyrun in order to evaluate stuff.

**Comment by jotoh98** [comment]
- worst case
- average case
- multiple instance variations
    - different distances between start and treasure location
    - relations and convergence of running time cases regarding treasure-start distance 
- miniature cli for pipelining tests
    - save and load files
-get overall running time constant for assuming linear running time (or other O-Classes)
