### ISSUE TITLE
Remove weird second option in GameManager

### ISSUE THREAD

**Issue by DorianRec** [jotoh98/treasureHunt#85]
(The blue line unter the first option is a second one)
<img width="218" alt="Bildschirmfoto 2019-12-18 um 22 03 55" src="https://user-images.githubusercontent.com/14947840/71123143-4b6d4800-21e2-11ea-82e4-2b93e8cb2f1a.png">

**Comment by 1-alex98** [comment]
This seems to be a java fx bug I really advice u leave it as it is, if u don't wanna spent hours and hours fixing it. It has no usability implecations...

**Comment by 1-alex98** [comment]
Lets close this because well we have no idea how to and it does not matter
